/* MAGNITUDE ANALYSIS */

-- Find total customers by country

SELECT country,
	   COUNT(customer_key) AS total_customers
	FROM customers
GROUP BY 1
ORDER BY 2 DESC;

-- Find total customers by gender

SELECT gender,
       COUNT(*)
	FROM customers
GROUP BY 1
ORDER BY 2 DESC;
       
-- Find total products by category

SELECT category,
       COUNT(product_id) AS number_of_products
	FROM products
GROUP BY 1
ORDER BY 2 DESC;

-- Find average costs in each category

SELECT category,
       AVG(cost) AS avg_cost
	FROM products
GROUP BY 1
ORDER BY 2 DESC;

-- Find total revenue generated for each category

SELECT products.category,
       SUM(sales.sales_amount) AS total_revenue
	FROM sales
LEFT JOIN products
	ON sales.product_key = products.product_key
GROUP BY 1
ORDER BY 2 DESC;

-- Find total revenue generated by each customer

SELECT customers.customer_key,
       customers.first_name,
       customers.last_name,
	   SUM(sales.sales_amount)
	FROM customers
LEFT JOIN sales
	ON customers.customer_key = sales.customer_key
GROUP BY 1, 2, 3
ORDER BY 4 DESC;

-- Find distribution of sold items across countries

SELECT customers.country,
	   SUM(sales.quantity) AS quantity_sold
	FROM customers
LEFT JOIN sales
	ON customers.customer_key = sales.customer_key
GROUP BY 1
ORDER BY 2 DESC;